export { Layout } from "./layout";
export { Header } from "./header";
export { About } from "./about";
export { Course } from "./course";
export { Exams } from "./exams";
export { Pricelist } from "./pricelist";
export { Events } from "./events";
export { Blog, BlogPage } from "./blog";
export { Contact } from "./contact";
export { Footer } from "./footer";
export { InitialTest } from "./initial-test";
